### ISSUE TITLE
ImportError: No module named cloghandler

### ISSUE THREAD

**Issue by hiloy** [WhaleShark-Team/cobra#1058]
执行./cobra.py --help，ConcurrentLogHandler模块已经安装了，cloghandler包找不到是为什么？
Traceback (most recent call last):
  File "./cobra.py", line 18, in <module>
    from cobra import main
  File "/home/cobra/cobra/__init__.py", line 21, in <module>
    from .log import logger
  File "/home/cobra/cobra/log.py", line 19, in <module>
    import cloghandler
ImportError: No module named cloghandler

要求的模块已安装：
Requirement already satisfied: Flask==0.10.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (0.10.1)
Requirement already satisfied: Flask-RESTful==0.3.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.3.6)
Requirement already satisfied: rarfile==2.7 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (2.7)
Requirement already satisfied: prettytable==0.7.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.7.2)
Requirement already satisfied: requests==2.6.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.6.2)
Requirement already satisfied: pytest==3.0.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (3.0.6)
Collecting pip==9.0.1 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl
Requirement already satisfied: phply==1.0.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: Werkzeug==0.11.9 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (0.11.9)
Requirement already satisfied: ConcurrentLogHandler==0.9.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 10)) (0.9.1)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1)) (0.24)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/site-packages (from Flask-RESTful==0.3.6->-r requirements.txt (line 2)) (2018.4)
Requirement already satisfied: six>=1.3.0 in /usr/local/lib/python2.7/site-packages (from Flask-RESTful==0.3.6->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: aniso8601>=0.82 in /usr/local/lib/python2.7/site-packages (from Flask-RESTful==0.3.6->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: py>=1.4.29 in /usr/local/lib/python2.7/site-packages (from pytest==3.0.6->-r requirements.txt (line 6)) (1.5.3)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from pytest==3.0.6->-r requirements.txt (line 6)) (39.0.1)
Requirement already satisfied: ply in /usr/local/lib/python2.7/site-packages (from phply==1.0.0->-r requirements.txt (line 8)) (3.11)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 1)) (1.0)

**Comment by hiloy** [comment]
已解决，设置PYTHONPATH环境变量，将模块安装路径加入Python搜索路径sys.path中
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
