### ISSUE TITLE
ImportError: No module named phply.phplex

### ISSUE THREAD

**Issue by hiloy** [WhaleShark-Team/cobra#1059]
执行./cobra.py --help  提示这个错误，phply模块安装路径已经加入sys.path了
Traceback (most recent call last):
  File "./cobra.py", line 18, in <module>
    from cobra import main
  File "/home/wcobra/cobra/__init__.py", line 22, in <module>
    from . import cli, api, config
  File "/home/wcobra/cobra/cli.py", line 18, in <module>
    from .engine import scan, Running
  File "/home/wcobra/cobra/engine.py", line 28, in <module>
    from .parser import scan_parser
  File "/home/wcobra/cobra/parser.py", line 14, in <module>
    from phply.phplex import lexer  # 词法分析
ImportError: No module named phply.phplex
BullseyeCoverage 8.4.4 error 15: Cannot open /home/wcobra/test.cov. COVFILE is not set, errno=2. Executable is python

**Comment by hiloy** [comment]
问题已解决，多个python环境导致

**Comment by Mr89898** [comment]
> 问题已解决，多个python环境导致

你好我也出现了这个问题，请问您如何解决这个问题
