### ISSUE TITLE
TypeError: verify() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by 823320816** [WhaleShark-Team/cobra#1344]
### System and Python Environment

System:Kali linux
Python: 2.7
Cobra:Cobra-Java

### Description

Traceback (most recent call last):
  File "/root/Downloads/cobra-Cobra-Java_1/cobra-Cobra-Java/cobra/engine.py", line 363, in process
    vul_results = Core(self.target_directory, vulnerability, self.sr, 'project name', ['whitelist1', 'whitelist2'], test=is_test, index=index).scan()
  File "/root/Downloads/cobra-Cobra-Java_1/cobra-Cobra-Java/cobra/engine.py", line 687, in scan
    res = p.verify(self)
TypeError: verify() takes exactly 1 argument (2 given)

**Comment by BlBana** [comment]
fixd
