### ISSUE TITLE
运行 ./cobra.py --help出错

### ISSUE THREAD

**Issue by liutuo008** [WhaleShark-Team/cobra#1388]
root@root:~/gongju/cobra# ./cobra.py --help
Traceback (most recent call last):
  File "./cobra.py", line 18, in <module>
    from cobra import main
  File "/root/gongju/cobra/cobra/__init__.py", line 21, in <module>
    from .log import logger
  File "/root/gongju/cobra/cobra/log.py", line 19, in <module>
    import cloghandler
ImportError: No module named cloghandler

**Comment by zero4703** [comment]
升级python版本到3.0以上试下？

**Comment by liutuo008** [comment]
我尝试一下，感谢回复




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年04月09日 23:30，zero4703 写道：

升级python版本到3.0以上试下？

**Comment by BlBana** [comment]
这个是因为类库没有安装，需要安装相应类库

`pip install -r requirements.txt`
